### PR TITLE
Update binary action

### PR DESCRIPTION
**Pull request by ironoa**

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
Very nice refactors! :100: 

Maybe we could use the new role in the main playbook? We could extract the code from `ansible/roles/polkadot-validator/tasks/service.yml` that is present in the new role and, in the main playbook, call the new role after polkadot-validator, wdyt?

**Review by fgimenez — COMMENTED** [review]
It would be also nice to add molecule tests to the new role and include them on CI.

**Comment by ironoa** [comment]
> It would be also nice to add molecule tests to the new role and include them on CI.

I knew you would have said so, I was working on it in this other branch actually ;-) Just few tunes missing.
https://github.com/w3f/polkadot-secure-validator/tree/update-binary-molecule

**Comment by ironoa** [comment]
> Very nice refactors! 💯
> 
> Maybe we could use the new role in the main playbook? We could extract the code from `ansible/roles/polkadot-validator/tasks/service.yml` that is present in the new role and, in the main playbook, call the new role after polkadot-validator, wdyt?

I totally agree with you thanks for the tip, it's great for the sake of dry !!
I had to implement it into the validator role, because the session task really need the binary to be already started.
Please tell me wdyt

**Comment by ironoa** [comment]
https://github.com/w3f/infrastructure/issues/319

**Comment by ironoa** [comment]
Successfully tested even with a local trigger: deployed a validator to my personal gcp

**Comment by fgimenez** [comment]
> I had to implement it into the validator role, because the session task really needs the binary to be there and already started.
> Please tell me wdyt

Looks very good, thanks!

**Review by fgimenez — APPROVED** [review]

**Review by pampatzoglou — APPROVED** [review]

**Pull request merged**
